[package]
name = "Exit_all_LH_validators"
version = "0.1.0"
authors = ["Arxis75"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
